Update README.md
dxw/wpc pull request #41
Opened 2020-03-17 20:00 UTC by mallorydxw

2020-03-20 11:10 UTC, RobjS requested changes

2020-03-20 11:10 UTC, RobjS commented on README.md
> +- `config/server.php` - configuration that would normally go in `wp-config.php` (checked into the repository)
Would it be worth clarifying that even though checked in, this only runs within the dev container, not on the staging or prod environments?

2020-03-20 11:10 UTC, RobjS commented on README.md
> +- `script/console` - open a `/bin/sh` console inside the main continer
Minor typo: "continer" => "container"

2020-03-20 11:10 UTC, RobjS commented on README.md
> +- [Docker Compose](https://docs.docker.com/compose/install/)
The Docker Desktop installation now includes Docker Compose. So this wouldn't be needed if they'd installed Docker via the previous link.

2020-03-23 13:36 UTC, mallorydxw commented
@RobjS Thanks! Resolved all three. Ready for another review.

2020-03-23 16:39 UTC, RobjS approved these changes

2020-03-23 17:23 UTC, merged